// Bank Soal Terstruktur & Unik (CPNS & UTBK)
const quizCategories = {
    cpns: {
        title: "CPNS & PPPK (Soal HOTS)",
        description: "Latihan Soal SKD Lengkap: TWK, TIU, & TKP Berstandar BKN",
        questions: [
            // TWK
            { question: "Indonesia menghadapi era digitalisasi di mana budaya asing sangat cepat masuk. Langkah konkret pengamalan Pancasila Sila ke-3 dalam menjaga integrasi bangsa di era digital adalah...", options: ["Menolak seluruh produk budaya luar", "Menyaring informasi serta memanfaatkan media sosial untuk mengamplifikasi narasi kebangsaan dan toleransi", "Membatasi akses internet masyarakat", "Melaporkan setiap akun media sosial yang mengkritik pemerintah"], answer: 1, explanation: "Sila ke-3 di era digital diwujudkan dengan menggunakan teknologi secara positif demi mempererat persatuan." },
            { question: "Seorang staf kementerian menemukan celah keamanan (bug) pada aplikasi pelayanan publik. Tindakan yang mencerminkan nilai Bela Negara 'Sadar Berbangsa dan Bernegara' adalah...", options: ["Memperbaiki bug secara diam-diam", "Melaporkan temuan tersebut segera kepada tim siber internal dan atasan untuk mitigasi risiko", "Mengunggah temuan bug ke media sosial", "Mengabaikannya karena bukan tugas utamanya"], answer: 1, explanation: "Sadar Berbangsa dan Bernegara diwujudkan melalui tanggung jawab profesional sesuai prosedur resmi." },
            { question: "Sumpah Pemuda 1928 mencetuskan 'Satu Nusa, Satu Bangsa, dan Bahasa Persatuan'. Secara substansial hal ini menjadi fondasi...", options: ["Sistem pemerintahan parlementer", "Identitas nasional dan kesadaran multikulturalisme dalam bingkai NKRI", "Dominasi suku tertentu", "Penghapusan bahasa daerah"], answer: 1, explanation: "Sumpah Pemuda menyatukan latar belakang yang beragam menjadi satu identitas nasional." },
            { question: "Pelaksanaan politik luar negeri Indonesia yang 'Bebas Aktif' ditunjukkan dengan sikap...", options: ["Mendukung salah satu blok kekuatan dunia", "Proaktif mendorong perdamaian dunia melalui diplomasi multilateral tanpa terikat pakta militer", "Bersikap netral pasif", "Memutus hubungan diplomatik dengan negara berkonflik"], answer: 1, explanation: "Bebas Aktif berarti tidak terikat pakta militer dan proaktif mengupayakan perdamaian dunia." },
            { question: "Diskriminasi pelayanan publik berdasarkan SARA merupakan pelanggaran Pancasila, khususnya Sila ke-...", options: ["Sila ke-1", "Sila ke-2", "Sila ke-3", "Sila ke-5"], answer: 1, explanation: "Sila ke-2 menjamin kesetaraan derajat dan hak setiap manusia tanpa diskriminasi." },
            { question: "Pokok pikiran pertama Pembukaan UUD 1945 tentang negara melindungi segenap bangsa Indonesia merupakan penjabaran Sila ke-...", options: ["Sila ke-1", "Sila ke-2", "Sila ke-3", "Sila ke-4"], answer: 2, explanation: "Pokok pikiran pertama Pembukaan UUD 1945 adalah Pokok Pikiran Persatuan (Sila ke-3)." },
            { question: "Guna mencegah praktek KKN di lingkungan pemerintahan, prinsip Good Governance yang paling krusial diterapkan adalah...", options: ["Sentralisasi kewenangan", "Transparansi, akuntabilitas, dan partisipasi publik", "Peningkatan anggaran operasional pimpinan", "Membatasi pengawasan eksternal"], answer: 1, explanation: "Good Governance berdiri atas pilar transparansi dan akuntabilitas publik." },
            { question: "Jiwa besar tokoh pendiri bangsa dalam perubahan frasa Sila Pertama pada 18 Agustus 1945 mencerminkan sikap...", options: ["Mempertahankan pendapat pribadi", "Mengutamakan persatuan dan kesatuan nasional di atas kepentingan kelompok", "Keinginan mempercepat persidangan", "Keputusan pihak asing"], answer: 1, explanation: "Perubahan frasa sila pertama dilakukan demi keutuhan bangsa yang majemuk." },
            { question: "Kedudukan UUD 1945 menurut UU No. 12 Tahun 2011 adalah sebagai...", options: ["Hukum dasar tertulis yang menduduki posisi tertinggi", "Peraturan pelaksana teknis", "Aturan tambahan sejajar UU", "Konvensi tidak tertulis"], answer: 0, explanation: "UUD 1945 merupakan norma hukum dasar dan tertinggi di Indonesia." },
            { question: "Semboyan Bhinneka Tunggal Ika dipetik dari kitab kuno karya Empu Tantular, yaitu...", options: ["Kitab Nagarakretagama", "Kitab Sutasoma", "Kitab Arjunawiwaha", "Kitab Pararaton"], answer: 1, explanation: "Bhinneka Tunggal Ika terdapat dalam Kitab Sutasoma karangan Empu Tantular." },

            // TIU
            { question: "Jika semua ASN profesional berpakaian rapi. Sebagian orang berpakaian rapi memiliki integritas tinggi. Kesimpulan yang tepat adalah...", options: ["Semua ASN berintegritas tinggi", "Sebagian ASN profesional mungkin memiliki integritas tinggi", "Tidak ada ASN yang berpakaian rapi", "Semua orang berpakaian rapi adalah ASN"], answer: 1, explanation: "Karena hanya sebagian orang berpakaian rapi berintegritas, maka hubungan dengan ASN bersifat sebagian/mungkin." },
            { question: "Proyek ditargetkan selesai 30 hari oleh 20 pekerja. Setelah 10 hari, pekerjaan terhenti 4 hari. Berapa tambahan pekerja agar selesai tepat waktu?", options: ["3 orang", "4 orang", "5 orang", "6 orang"], answer: 2, explanation: "Sisa beban = 20x20 = 400. Sisa waktu = 16 hari. Pekerja butuh = 400/16 = 25. Tambahan = 25 - 20 = 5 orang." },
            { question: "Deret angka: 3, 6, 12, 21, 33, ... Angka berikutnya adalah...", options: ["42", "45", "48", "51"], answer: 2, explanation: "Pola selisih +3, +6, +9, +12, maka berikutnya +15 (33 + 15 = 48)." },
            { question: "KONTRAK : ABROGASI = JANJI : ...", options: ["PEMBATALAN", "PELANGGARAN", "SANKSI", "PIUTANG"], answer: 0, explanation: "Pembatalan resmi kontrak adalah abrogasi, pembatalan janji adalah pembatalan." },
            { question: "Uang dibagi A, B, C dengan perbandingan 2 : 3 : 5. Jika selisih C dan A Rp 600.000, berapa uang B?", options: ["Rp 400.000", "Rp 600.000", "Rp 800.000", "Rp 1.000.000"], answer: 1, explanation: "Selisih C - A = 3 bagian = Rp 600.000 (1 bagian = Rp 200.000). Bagian B = 3 x Rp 200.000 = Rp 600.000." },
            { question: "Jika X = 0,85 + 1/4 dan Y = 1,10 - 0,05, maka...", options: ["X > Y", "X < Y", "X = Y", "Tidak dapat ditentukan"], answer: 0, explanation: "X = 0,85 + 0,25 = 1,10. Y = 1,05. Maka X > Y." },
            { question: "Sebuah bus berangkat pukul 07.15 kecepatan 60 km/jam jarak 180 km. Istirahat 30 menit. Tiba pukul...", options: ["10.15", "10.45", "11.15", "11.45"], answer: 1, explanation: "Waktu tempuh = 3 jam + 30 menit = 3,5 jam. Tiba = 07.15 + 03.30 = 10.45." },
            { question: "Jika 5a = 45 dan b = a - 3, nilai a^2 + b^2 adalah...", options: ["81", "117", "125", "144"], answer: 1, explanation: "a = 9, b = 6. a^2 + b^2 = 81 + 36 = 117." },
            { question: "A lebih tinggi dari B. B lebih tinggi dari C. D lebih tinggi dari B tapi lebih pendek dari A. Yang terpendek adalah...", options: ["A", "B", "C", "D"], answer: 2, explanation: "Urutan tinggi: A > D > B > C. Terpendek adalah C." },
            { question: "LARI : SEHAT = BELAJAR : ...", options: ["PINTAR", "UJI", "BUKU", "SEKOLAH"], answer: 0, explanation: "Lari berdampak Sehat. Belajar berdampak Pintar." },

            // TKP
            { question: "Anggota senior kesulitan mengoperasikan sistem baru. Sikap Anda sebagai ketua tim adalah...", options: ["Mengambil alih tugasnya", "Meminta pimpinan menggantinya", "Mengatur sesi mentoring khusus dan membagi tugas sesuai kapasitasnya", "Membiarkannya"], answer: 2, explanation: "Mengatur mentoring dan pembagian tugas cermin kepemimpinan berempati dan efektif." },
            { question: "Warga menerobos antrean dan marah-marah di loket. Sikap Anda...", options: ["Membalas membentak", "Meminta tenang, mendengarkan empati, dan mengarahkan ke loket pengaduan", "Meninggalkan loket", "Mengusirnya"], answer: 1, explanation: "Pelayanan publik mengedepankan pengendalian diri dan komunikasi persuasif." },
            { question: "Rekan kerja memanfaatkan waktu WFA untuk urusan pribadi hingga target terganggu. Sikap Anda...", options: ["Melaporkan ke atasan", "Mengingatkan secara personal komitmen target tim dan menawarkan bantuan", "Apatis", "Mengerjakan tugasnya"], answer: 1, explanation: "Pendekatan persuasi rekan sejawat menjaga profesionalisme dan kekompakan tim." },
            { question: "Pimpinan meminta laporan mendadak dalam 2 jam saat Anda mengerjakan tugas rutin. Sikap Anda...", options: ["Menolak", "Menerima, membuat skala prioritas, dan berkoordinasi pendelegasian tugas rutin", "Mengerjakan asal-asalan", "Mengarahkan ke orang lain"], answer: 1, explanation: "Pentingnya skala prioritas serta adaptabilitas dalam situasi mendesak." },
            { question: "Sistem AI baru diimplementasikan namun senior enggan belajar. Sikap Anda...", options: ["Mengikuti senior", "Proaktif mempelajari dan membuat panduan sederhana untuk senior", "Menggunakannya untuk diri sendiri saja", "Mengusulkan pembatalan"], answer: 1, explanation: "ASN berorientasi perubahan menjadi agen pembaru bagi lingkungan kerja." }
        ]
    },
    utbk: {
        title: "UTBK / SNBT (TPS & Literasi)",
        description: "Latihan Soal Tes Potensi Skolastik (TPS), Penalaran Kuantitatif, & Literasi",
        questions: [
            { question: "Rata-rata nilai 5 siswa adalah 80. Jika 1 nilai terkecil dikeluarkan, rata-rata 4 siswa sisanya 84. Nilai yang dikeluarkan adalah...", options: ["60", "64", "68", "72"], answer: 1, explanation: "Total awal = 400. Total sisa = 336. Nilai dikeluarkan = 400 - 336 = 64." },
            { question: "Jika p x q = p + q + 2, nilai dari 3 x 4 adalah...", options: ["7", "9", "11", "14"], answer: 1, explanation: "3 x 4 = 3 + 4 + 2 = 9." },
            { question: "Diskon beruntun 20% lalu diskon tambahan 10%. Total diskon efektif adalah...", options: ["28%", "30%", "32%", "35%"], answer: 0, explanation: "Harga awal 100 -> Diskon I = 80 -> Diskon II (10% x 80 = 8) -> Sisa 72. Total diskon = 28%." },
            { question: "Jika x^2 - y^2 = 36 dan x - y = 4, nilai rata-rata x dan y adalah...", options: ["4.5", "5.0", "6.0", "9.0"], answer: 0, explanation: "(x - y)(x + y) = 36 => 4(x + y) = 36 => x + y = 9. Rata-rata = 9/2 = 4.5." },
            { question: "Persegi panjang p=(2x+3) cm dan l=(x+1) cm. Keliling = 32 cm. Luasnya adalah...", options: ["55 cm²", "60 cm²", "66 cm²", "72 cm²"], answer: 0, explanation: "2(3x+4)=32 => 3x+4=16 => x=4. p=11, l=5. Luas = 55 cm²." },
            { question: "Kantong berisi 4 bola merah dan 6 bola biru. Diambil 2 bola sekaligus. Peluang keduanya biru adalah...", options: ["1/3", "2/5", "1/2", "3/5"], answer: 0, explanation: "C(6,2)/C(10,2) = 15 / 45 = 1/3." },
            { question: "Jika 3^(x+1) = 81, nilai 2^(2x - 1) adalah...", options: ["8", "16", "32", "64"], answer: 2, explanation: "x + 1 = 4 => x = 3. 2^(6 - 1) = 2^5 = 32." },
            { question: "Garis melalui (2, 5) dan tegak lurus y = 2x - 3 adalah...", options: ["y = -1/2 x + 6", "y = -2x + 9", "y = 1/2 x + 4", "y = -1/2 x + 4"], answer: 0, explanation: "m2 = -1/2. y - 5 = -1/2(x - 2) => y = -1/2 x + 6." },
            { question: "Median data: 4, 5, 7, 8, x, 12, 14 adalah 8. Nilai x agar jangkauan 10 adalah...", options: ["8", "9", "10", "11"], answer: 0, explanation: "Jangkauan = 14 - 4 = 10. Nilai x bisa 8 agar median tetap 8." },
            { question: "30 siswa: 18 suka MTK, 15 suka B.Inggris, 5 tidak suka keduanya. Banyak siswa suka KEDUANYA adalah...", options: ["5 orang", "8 orang", "10 orang", "12 orang"], answer: 1, explanation: "Suka minimal satu = 25. Suka keduanya = (18 + 15) - 25 = 8 orang." },
            { question: "5 siswa (D, C, E, A, B) antre. B di belakang A. C di antara D dan E. D paling depan. E di depan A. Urutan ke-3 adalah...", options: ["B", "C", "D", "E"], answer: 3, explanation: "Urutan dari depan: D, C, E, A, B. Urutan ke-3 adalah E." },
            { question: "Konjungsi tepat: 'Upaya menekan inflasi perlu diapresiasi, [...] dampaknya belum sepenuhnya dirasakan.'", options: ["Namun,", "Sehingga", "Karena", "Bahkan"], answer: 0, explanation: "Kata hubung pertentangan yang tepat adalah Namun,." },
            { question: "The main idea of 'AI increases productivity; however, ethical concerns regarding data privacy remain' is...", options: ["AI is unsafe", "AI increases productivity but raises ethical data privacy concerns", "Data privacy is not an issue", "Productivity is all that matters"], answer: 1, explanation: "Main idea menyatakan AI meningkatkan produktivitas sekaligus menimbulkan isu privasi." },
            { question: "Penggunaan koma tepat terdapat pada...", options: ["Ibu membeli buah pisang, apel, dan jeruk di pasar.", "Karena hujan, maka kami libur.", "Dia rajin, tetapi, tidak teliti.", "Di Medan kami mengunjungi Toba."], answer: 0, explanation: "Rincian 3 unsur atau lebih wajib menggunakan koma sebelum kata 'dan'." },
            { question: "Bentuk baku dari kata yang sering salah ditulis 'hirarki' adalah...", options: ["Hierarki", "Hirarki", "Herarki", "Hirarkis"], answer: 0, explanation: "Berdasarkan KBBI, bentuk baku kata tersebut adalah Hierarki." }
        ]
    }
};
